"""
AI-Generated Filters for AI Trader.

This directory contains filters automatically generated by the
Self-Upgrade System. Each filter has been:

1. Suggested by Claude based on losing pattern analysis
2. Validated by AST security checker
3. Tested via walk-forward backtesting
4. Deployed only if robustness score >= 60%

Filters here can be automatically rolled back if performance degrades.
"""
